### ISSUE TITLE
Getting java.net.SocketTimeoutException when used historical service for fetching intraday data for nse_index instruments.

### ISSUE THREAD

**Issue by nikhil2108** [rishabh9/riko#1]
I get timeout exception, when I try to use historical service for fetching 1min or 5min olhc data for "nifty_50" or "nifty_bank". This works fine for all nse_eq instruments.

If I call api by using postman for "nifty_50" or "nifty_bank", I get data successfully.

Code:-
`List<Candle> candles = historicalService.getOhlc("nse_index", "nifty_bank", "5MINUTE", "26-10-2018", "28-11-2018").get().getData();`

Stacktrace:-

```
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at com.strategy.tradebot.RenkoBT.generateHistoricalRenko(RenkoBacktest.java:150)
	at com.strategy.tradebot.RenkoBT.<init>(RenkoBacktest.java:119)
	at com.strategy.tradebot.RenkoBacktest.main(RenkoBacktest.java:52)
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
	at okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:146)
	at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:125)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.github.rishabh9.riko.upstox.common.interceptors.HttpErrorLoggingInterceptor.intercept(HttpErrorLoggingInterceptor.java:46)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.github.rishabh9.riko.upstox.common.interceptors.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:56)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rishabh9** [comment]
`SocketTimeoutException` indicates only two possible situations:
- There is a network issue.
- Upstox servers are not responding quick enough.

Especially today (`2018-11-29`), Upstox was having issues in their Historical API. 

You could try two things here:
- You could point Riko to Upstox's staging server and see if the issue persists. Upstox claims their staging setup performs better at the moment. Please see [this](https://github.com/rishabh9/riko/wiki/Requirements,-Configuration-&-Progaurd#configuration) to configure the same. 
- You could also tweak the read/connect timeout as mentioned [here](https://github.com/rishabh9/riko/wiki/Requirements,-Configuration-&-Progaurd#configuration).

**Comment by nikhil2108** [comment]
I did point to staging server also modified read and connect timeout arguments. Now I barely get timeout exception (1/20 times). This resolved my issue. Thanks.
My only concern is about slow response from Upstox server, as this might lead some lag in trade calls from my strategy. I hope they will make it quicker soon.

**Comment by nikhil2108** [comment]
The worst part is sometimes upstox apis return 500 internal server error.

10:11:37.235 [OkHttp https://api.upstox.com/...] ERROR com.github.rishabh9.riko.upstox.common.interceptors.HttpErrorLoggingInterceptor - ATTENTION! API endpoint: https://api.upstox.com/historical/ohlc/nse_eq/ibulhsgfin?interval=1MINUTE&start_date=30-11-2018&end_date=30-11-2018&format=json returned Status Code: 500 with Body: {"message": "Internal server error"}
java.util.concurrent.ExecutionException: retrofit2.adapter.java8.HttpException: HTTP 500
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)

**Comment by rishabh9** [comment]
Yes, I faced the same and reported it to them. And they have happily chosen
to ignore it.

**Comment by nikhil2108** [comment]
Regarding 500 and timeout issue:-
Upstox delvelopers are claiming that they have fixed these issues in staging endpoints.
https://upstox.com/forum/topic/1888/upstox-python-sdk-release-beta

When I checked their Python code, I found that they have changed historical ohlc endpoint a bit.

https://staging-api.upstox.com/historical/NSE_EQ/ibulhsgfin/1?start_date=01-08-2018&end_date=07-08-2018

If you notice, there is no interval request param. Interval is part of url itself. Also, as mentioned on forum, we can get 7 days data max in single request. But the good part is they are now giving last 6 months of data for intraday intervals.(this was 1 month for 1min interval before).

Also the response is like below-

`{
    "code": 200,
    "status": "OK",
    "timestamp": "2018-12-02T17:58:26+05:30",
    "message": "historical-data",
    "data": [
        "1533095100000,1298.95,1304.0,1297.1,1298.05,15688",
        "1533095160000,1298.0,1298.0,1280.25,1280.3,19359",
        "1533095220000,1281.3,1287.85,1280.0,1280.45,25408"
]}`

I am not sure, but we may not face timeout and 500 issues on this particular endpoint.
So, by any chance are you planning to update library to accommodate these changes?

**Comment by rishabh9** [comment]
Supporting staging-server of Upstox is going to be a pain. The staging server works as testing server before promoting to production. So there are high chances that URL endpoints may change or parameters may change, and I'll not get any update about it from Upstox directly for I am a third party developer. I'll have to rely on people like you to let me know when things break. Also, there's no documentation about the API endpoints of the staging server.
Having said all that, I can provide a stable product (for Upstox staging) only when I have the complete documentation of their new API endpoints and there is someway to know when there are changes to the staging endpoints.

**Comment by nikhil2108** [comment]
Yes, makes sense. I think they have fixed these issues. I didn't get any timeouts or 500 in complete day(03-12-2018). Although there was a case when socket connection broke in between and application crashed abruptly.

`FATAL com.strategy.tradebot.UpstoxWebSocketSubscriber - Error occurred: {}
java.lang.Throwable: Error from Upstox: null
        at com.strategy.tradebot.UpstoxWebSocketSubscriber.onNext(UpstoxWebSocketSubscriber.java:59) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at com.strategy.tradebot.UpstoxWebSocketSubscriber.onNext(UpstoxWebSocketSubscriber.java:17) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(SubmissionPublisher.java:1307) ~[?:?]
        at java.util.concurrent.SubmissionPublisher$BufferedSubscription.takeItems(SubmissionPublisher.java:1296) ~[?:?]
        at java.util.concurrent.SubmissionPublisher$BufferedSubscription.consume(SubmissionPublisher.java:1253) ~[?:?]
        at java.util.concurrent.SubmissionPublisher$ConsumerTask.exec(SubmissionPublisher.java:930) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
08:36:28.928 [ForkJoinPool-1-worker-3] FATAL com.strategy.tradebot.UpstoxWebSocketSubscriber - Error occurred: {}
java.io.EOFException: null
        at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:213) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[tradebot-0.0.1-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]`

Did you face this kind of issue before? I am thinking of reconnecting to websocket in onError() callback. Not sure whether this will work.

Please suggest if you have any better solution for this issue.

**Comment by rishabh9** [comment]
You are thinking in the correct direction. Currently `onError()` is the only way to identify disconnection. But it will also be called for other errors and we cannot differentiate b/w them at the moment. Thus, the websocket connect and/or disconnect logic should be independent of any other logic/flow/etc in your system, because. you maybe calling `reconnect()` for a non-disconnect error. Also, any `reconnect()` should have a call to the `websocket.disconnect()` before calling `websocket.connect()` again. This will ensure that you release resources related to previous connection.

**Comment by nikhil2108** [comment]
Yes will take care of disconnecting socket before connecting everytime. Thanks.

**Comment by nikhil2108** [comment]
I know this is not an issue of library and because of some weird response from Upstox apis, just in case you faced this too.

`java.util.concurrent.ExecutionException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at com.strategy.tradebot.Renko.isDownBrick(Renko.java:442)
        at com.strategy.tradebot.Renko.checkRenkoBrick(Renko.java:809)
        at com.strategy.tradebot.UpstoxWebSocketSubscriber.onNext(UpstoxWebSocketSubscriber.java:42)
        at com.strategy.tradebot.UpstoxWebSocketSubscriber.onNext(UpstoxWebSocketSubscriber.java:16)
        at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(SubmissionPublisher.java:1307)
        at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.takeItems(SubmissionPublisher.java:1296)
        at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consume(SubmissionPublisher.java:1253)
        at java.base/java.util.concurrent.SubmissionPublisher$ConsumerTask.exec(SubmissionPublisher.java:930)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)`

I am getting this exception 1/20 times for historical apis. I am not able to track the response in such cases. By any chance, do you have an idea about this? Also, if I could record the response from Upstox apis, I would escalate this on their forum.

**Comment by rishabh9** [comment]
I haven't faced it yet. What API call throws this error? You can set log level to `DEBUG` for `com.github.rishabh9.riko.upstox.common.ServiceGenerator` to log every request/response going through Riko. Btw, please raise this as a separate issue, so we  can track it better.
